---
variables:
  serviceConnectionToAzure: myapp-rg
  appName: ajs-php-mysql
  phpVersion: 7.4
  
trigger:
- master

pool:
  vmImage: 'ubuntu-18.04'

steps:
- script: |
    sudo update-alternatives --set php /usr/bin/php$(phpVersion)
    sudo update-alternatives --set phar /usr/bin/phar$(phpVersion)
    sudo update-alternatives --set phpdbg /usr/bin/phpdbg$(phpVersion)
    sudo update-alternatives --set php-cgi /usr/bin/php-cgi$(phpVersion)
    sudo update-alternatives --set phar.phar /usr/bin/phar.phar$(phpVersion)
    php -version
  displayName: 'Use PHP version $(phpVersion)'

- script: composer install --no-interaction --prefer-dist
  displayName: 'composer install'

# add these as the last steps (below all the other `task` items under `steps`)
# to deploy to your app service
- task: ArchiveFiles@1
  displayName: Archive files
  inputs:
    rootFolder: $(System.DefaultWorkingDirectory)
    includeRootFolder: false
    archiveType: zip

- task: PublishBuildArtifacts@1
  displayName: Publish Artifact
  inputs:
    PathtoPublish: $(build.artifactstagingdirectory)

#- task: AzureWebApp@1
#  displayName: Azure Web App Deploy
#  inputs:
#    azureSubscription: $(serviceConnectionToAzure)
#    appType: webAppLinux
#    appName: $(appName)
#    package: $(build.artifactstagingdirectory)/**/*.zip
#    runtimeStack: 'PHP|7.4'
#    appSettings: '-SCM_DO_BUILD_DURING_DEPLOYMENT true'

- task: AzureRmWebAppDeployment@4
  displayName: 'Azure App Service Deploy: ajs-php-mysql'
  inputs:
    azureSubscription: $(serviceConnectionToAzure)
    appType: webAppLinux
    WebAppName: $(appName)
    package: $(build.artifactstagingdirectory)/**/*.zip
    RuntimeStack: 'PHP|7.4'
    # ScriptType: 'File Path'
    # ScriptPath: scripts/post.sh
